apiVersion: v1
kind: Secret
metadata:
  name: {{ include "links2go.fullname" . }}-secret
  labels:
    {{- include "links2go.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.redis.enabled }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- else if .Values.externalRedis.password }}
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ "" | b64enc | quote }}
  {{- end }}