name: Docker Image Cleanup

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        image: [backend, frontend]
    
    steps:
      - name: Delete old untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_PREFIX }}-${{ matrix.image }}
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
      
      - name: Delete old pre-release images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_PREFIX }}-${{ matrix.image }}
          package-type: container
          min-versions-to-keep: 5
          delete-only-pre-release-versions: true
      
      - name: Keep only recent development images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_PREFIX }}-${{ matrix.image }}
          package-type: container
          min-versions-to-keep: 10
          ignore-versions: '^(latest|stable|v?\d+\.\d+\.\d+)$'